spring:
  #redis配置
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password: 'redis123'
    timeout: 20000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  #数据库配置
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      datasource:
        master:
          username: binance
          password: Qazwsx2021@@~!
          url: jdbc:mysql://47.241.225.236:3306/india?useUnicode=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid: # 以下参数针对每个库可以重新设置druid参数
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 6000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #Oracle需要打开注释
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
              enabled: true
              url-pattern: /druid/*
              #login-username: admin
              #login-password: admin
            filter:
              stat:
                log-slow-sql: true
                slow-sql-millis: 1000
                merge-sql: false
              wall:
                config:
                  multi-statement-allow: true
# 配置slq打印日志
mybatis-plus:
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#存取款配制
order:
  config:
    merchId: 8
    apiToken: f42c97ef4333eb9676b6b3b3c57dd2e7c27dcad5
    orderUrl: http://47.241.170.206/api/payTest/order
    orderCallbackUrl: http://pay.hishow.xyz/orderCallback/order
    collectionUrl: http://47.241.170.206/api/payTest/collection
    collectionCallbackUrl: http://pay.hishow.xyz/orderCallback/collection








